# PySNMP SMI module. Autogenerated from smidump -f python RFC-1212
# by libsmi2pysnmp-0.0.7-alpha at Wed Nov 18 12:29:29 2009,
# Python version (2, 6, 4, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( ObjectName, ) = mibBuilder.importSymbols("RFC1155-SMI", "ObjectName")
( DisplayString, ) = mibBuilder.importSymbols("RFC1158-MIB", "DisplayString")
( Bits, Integer32, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "MibIdentifier", "TimeTicks")

# Types

class Counter(Integer32):
    subtypeSpec = Integer32.subtypeSpec+constraint.ValueRangeConstraint(-1,0)
    pass

class Gauge(Integer32):
    subtypeSpec = Integer32.subtypeSpec+constraint.ValueRangeConstraint(-1,0)
    pass

class IpAddress(OctetString):
    subtypeSpec = OctetString.subtypeSpec+constraint.ValueSizeConstraint(4,4)
    fixedLength = 4
    pass

class Opaque(OctetString):
    pass

class TimeTicks(Integer32):
    subtypeSpec = Integer32.subtypeSpec+constraint.ValueRangeConstraint(-1,0)
    pass


# Exports

# Types
mibBuilder.exportSymbols("RFC-1212", Counter=Counter, Gauge=Gauge, IpAddress=IpAddress, Opaque=Opaque, TimeTicks=TimeTicks)

