# PySNMP SMI module. Autogenerated from smidump -f python RFC1158-MIB
# by libsmi2pysnmp-0.0.7-alpha at Wed Nov 18 12:31:19 2009,
# Python version (2, 6, 4, 'final', 0)

# Imported just in case new ASN.1 types would be created
from pyasn1.type import constraint, namedval

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( Counter, Gauge, IpAddress, NetworkAddress, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, mgmt, ) = mibBuilder.importSymbols("RFC1155-SMI", "Counter", "Gauge", "IpAddress", "NetworkAddress", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "mgmt")
( Bits, Integer32, MibIdentifier, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "MibIdentifier", "TimeTicks")

# Types

class DisplayString(OctetString):
    pass


# Objects

mib_2 = MibIdentifier((1, 3, 6, 1, 2, 1)).setLabel("mib-2")
system = MibIdentifier((1, 3, 6, 1, 2, 1, 1))
interfaces = MibIdentifier((1, 3, 6, 1, 2, 1, 2))
at = MibIdentifier((1, 3, 6, 1, 2, 1, 3))
ip = MibIdentifier((1, 3, 6, 1, 2, 1, 4))
icmp = MibIdentifier((1, 3, 6, 1, 2, 1, 5))
tcp = MibIdentifier((1, 3, 6, 1, 2, 1, 6))
udp = MibIdentifier((1, 3, 6, 1, 2, 1, 7))
egp = MibIdentifier((1, 3, 6, 1, 2, 1, 8))
transmission = MibIdentifier((1, 3, 6, 1, 2, 1, 10))
snmp = MibIdentifier((1, 3, 6, 1, 2, 1, 11))

# Augmentions

# Exports

# Types
mibBuilder.exportSymbols("RFC1158-MIB", DisplayString=DisplayString)

# Objects
mibBuilder.exportSymbols("RFC1158-MIB", mib_2=mib_2, system=system, interfaces=interfaces, at=at, ip=ip, icmp=icmp, tcp=tcp, udp=udp, egp=egp, transmission=transmission, snmp=snmp)

